"""adds brand name to drugs

Revision ID: 1db1e758b39c
Revises: b608c9bcf0e3
Create Date: 2021-01-22 05:54:55.888039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db1e758b39c'
down_revision = 'b608c9bcf0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug', sa.Column('brand_name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug', 'brand_name')
    # ### end Alembic commands ###
