"""adds timestamp to posts

Revision ID: 39c16cd10ee8
Revises: 4907810d149c
Create Date: 2021-01-24 06:34:07.126310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c16cd10ee8'
down_revision = '4907810d149c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
