"""adds drug name to tags

Revision ID: 4907810d149c
Revises: db5f67d8454f
Create Date: 2021-01-24 06:12:52.984286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4907810d149c'
down_revision = 'db5f67d8454f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drug_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('drug_name')

    # ### end Alembic commands ###
