"""user relations

Revision ID: 60714e800371
Revises: 39c16cd10ee8
Create Date: 2021-01-24 06:44:32.553396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60714e800371'
down_revision = '39c16cd10ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('key', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('key', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
