"""simplify Tag table

Revision ID: 785dc5ce2e8c
Revises: 60714e800371
Create Date: 2021-01-25 06:45:35.736486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785dc5ce2e8c'
down_revision = '60714e800371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.drop_column('condition_name')
        batch_op.drop_column('drug_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drug_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('condition_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
