"""condition and drug relation

Revision ID: ea25558f704d
Revises: 
Create Date: 2021-01-12 16:52:00.497240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea25558f704d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_name'), 'condition', ['name'], unique=True)
    op.create_table('drug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_name'), 'drug', ['name'], unique=True)
    op.create_table('intervention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('no_studies', sa.Integer(), nullable=True),
    sa.Column('no_tested', sa.Integer(), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_score'), 'intervention', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervention_score'), table_name='intervention')
    op.drop_table('intervention')
    op.drop_index(op.f('ix_drug_name'), table_name='drug')
    op.drop_table('drug')
    op.drop_index(op.f('ix_condition_name'), table_name='condition')
    op.drop_table('condition')
    # ### end Alembic commands ###
